require: rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics:
  Exclude:
    - 'hearth/spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'hearth/spec/**/*.rb'
    - 'hearth/lib/hearth/middleware/retry.rb'

Metrics/BlockLength:
  Exclude:
    - 'hearth/spec/**/*.rb'
    - 'hearth/lib/hearth/middleware/retry.rb'

Metrics/ClassLength:
  Exclude:
    - 'hearth/lib/hearth/http/client.rb'
    - 'hearth/lib/hearth/middleware/send.rb'
    - 'hearth/lib/hearth/retry/client_rate_limiter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'hearth/lib/hearth/middleware/retry.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'hearth/spec/**/*.rb'
    - 'hearth/lib/hearth/middleware/*.rb'

Metrics/ParameterLists:
  Exclude:
    - 'hearth/lib/hearth/middleware/auth.rb'
    - 'hearth/lib/hearth/middleware/send.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'hearth/lib/hearth/middleware/retry.rb'

Style/Documentation:
  Exclude:
    - 'hearth/spec/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'hearth/lib/hearth/query/param_matcher.rb'
