AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - 'build/**/*'
    - 'tasks/release/**/*'
    - 'vendor/**/*'

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - '**/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - '**/spec/**/*.rb'

Naming/FileName:
  Exclude:
    - '**/spec/**/*.rb'
    - 'gems/smithy-client/lib/smithy-client.rb'
    - 'gems/smithy-server/lib/smithy-server.rb'

Style/BlockComments:
  Exclude:
    - '**/spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - '**/spec/**/*.rb'
