AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'build/**/*'
    - 'tasks/release/**/*'
    - 'vendor/**/*'

Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Exclude:
    - 'projections/**/*/errors.rb'
    - 'projections/**/*/types.rb'

Layout/EmptyLinesAroundModuleBody:
  Exclude:
    - 'projections/**/*/errors.rb'
    - 'projections/**/*/types.rb'

Metrics/AbcSize:
  Exclude:
    - 'gems/smithy/lib/smithy/forge/client.rb'
    - 'gems/smithy/lib/smithy/anvil/client/views/shapes.rb'

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - '**/spec/**/*.rb'

Naming/FileName:
  Exclude:
    - '**/spec/**/*.rb'
    - 'gems/smithy-client/lib/smithy-client.rb'
    - 'gems/smithy-server/lib/smithy-server.rb'

Style/BlockComments:
  Exclude:
    - '**/spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - '**/spec/**/*.rb'
