AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'tasks/release/**/*'
    - 'build/**/*'

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - '**/spec/**/*.rb'

Naming/FileName:
  Exclude:
    - '**/spec/**/*.rb'
    - 'gems/smithy-client/lib/smithy-client.rb'
    - 'gems/smithy-server/lib/smithy-server.rb'

Style/BlockComments:
  Exclude:
    - '**/spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - '**/spec/**/*.rb'