AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/sample-schema.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
