inherit_from:
  - ../hearth/.rubocop.yml

inherit_mode:
  override:
    - Exclude

AllCops:
  Exclude:
    - 'projections/**/*'
    - '**/build/**/*'

Metrics:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/Documentation:
  Exclude:
    - '**/*_spec.rb'

Lint/EmptyClass:
  Exclude:
    - 'smithy-ruby-codegen-test/integration-specs/params_spec.rb'

