AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'projections/**/*'
    - '**/build/**/*'

Metrics:
  Exclude:
    - '**/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/**/*_spec.rb'

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Exclude:
    - '**/integration-specs/*_spec.rb'

Lint/EmptyClass:
  Exclude:
    - 'smithy-ruby-codegen-test/integration-specs/params_spec.rb'