inherit_from:
  - ../hearth/.rubocop.yml

AllCops:
  Exclude:
    - 'projections/**/*'
    - '**/build/**/*'

Metrics:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/Documentation:
  Exclude:
    - '**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyClass:
  Exclude:
    - 'smithy-ruby-codegen-test/integration-specs/params_spec.rb'

