require: rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/hearth/middleware/retry.rb'
    - 'lib/hearth/middleware/send.rb'
    - 'lib/hearth/cbor/encoder.rb'
    - 'lib/hearth/cbor/decoder.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/hearth/middleware/retry.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/hearth/http/client.rb'
    - 'lib/hearth/middleware/send.rb'
    - 'lib/hearth/retry/client_rate_limiter.rb'
    - 'lib/hearth/cbor/encoder.rb'
    - 'lib/hearth/cbor/decoder.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/hearth/middleware/retry.rb'
    - 'spec/hearth/cbor/cbor_spec.rb'
    - 'lib/hearth/cbor/encoder.rb'
    - 'lib/hearth/cbor/decoder.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/hearth/middleware/*.rb'
    - 'lib/hearth/cbor/encoder.rb'
    - 'lib/hearth/cbor/decoder.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/hearth/middleware/auth.rb'
    - 'lib/hearth/middleware/send.rb'
    - 'lib/hearth/middleware/event_stream_handlers.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/hearth/middleware/retry.rb'
    - 'lib/hearth/cbor/encoder.rb'
    - 'lib/hearth/cbor/decoder.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'lib/hearth/query/param_matcher.rb'
