AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Gemspec/RequireMFA:
  Exclude:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/hearth/middleware/send.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/hearth/middleware_builder.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/hearth/middleware/send.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'lib/hearth/query/param_matcher.rb'
