AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/hearth/http/client.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Gemspec/RequireMFA:
  Exclude:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/hearth/middleware/send.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/hearth/http/client.rb'
    - 'lib/hearth/middleware_builder.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/hearth/middleware/send.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'lib/hearth/query/param_matcher.rb'
