AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics:
  Exclude:
    - 'spec/**/*.rb'

# For some reason, Metrics disable doesn't cover this
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Gemspec/RequireMFA:
  Exclude:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Exclude:
    - 'lib/hearth/middleware_builder.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/hearth/middleware/retry.rb'
    - 'lib/hearth/middleware/send.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'lib/hearth/query/param_matcher.rb'
