AllCops:
  NewCops: enable

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
