AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/seahorse/middleware_builder.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
