name: Benchmark

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write # required for OIDC
  contents: read

env:
  java_version: 17

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Build SDK
        run: bundle exec rake codegen:build

      - name: Benchmark
        run: EXECUTION_ENV=github-action bundle exec rake benchmark:run

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::469596866844:role/aws-sdk-ruby-performance-reporter
          role-session-name: benchmark-report
          aws-region: us-west-2

      - name: Archive benchmark report
        run: |
          GH_REPO=${{github.repository}} GH_REF=${{github.head_ref}} GH_EVENT=${{github.event_name}} bundle exec rake benchmark:archive

      - name: Upload benchmark metrics
        run: |
          GH_REPO=${{github.repository}} GH_REF=${{github.head_ref}} GH_EVENT=${{github.event_name}} bundle exec rake benchmark:put-metrics
