name: Smithy Ruby Codegen CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 17
  ruby_version: 3.3

jobs:
  whitelabel-rbs:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}

      - uses: actions/checkout@v4

      - name: Install gems
        run: |
          bundle config set --local with 'rbs test'
          bundle install

      - name: Build the SDK
        run: bundle exec rake codegen:build

      - name: steep check
        run: bundle exec rake steep:white_label

      - name: rbs:test
        run: bundle exec rake rbs:white_label

  codegen-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Supported ruby versions
        ruby: [jruby-9.4, '3.0', 3.1, 3.2, 3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'test'
          bundle install

      - name: Build SDK
        run: bundle exec rake codegen:build

      - name: WhiteLabel Integration tests
        run: bundle exec rake test:white_label

      - name: Smithy Core Endpoint Specs
        run: bundle exec rake test:smithy-core-endpoint-tests

  codegen-rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'development'
          bundle install

      - name: Rubocop
        run: bundle exec rake rubocop:codegen

