name: Smithy Ruby Codegen CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 8

jobs:
  generate-test-sdk:
    name: Generate the test SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: Build test SDK
      working-directory: codegen
      run:
        ./gradlew :smithy-ruby-codegen-test:build
    - name: Upload generated test SDK
      uses: actions/upload-artifact@v2
      with:
        name: white_label
        path: codegen/smithy-ruby-codegen-test/build/smithyprojections/smithy-ruby-codegen-test/white-label/ruby-codegen/white_label

  ruby-rbs-type-check:
    needs: [generate-test-sdk]
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - uses: actions/checkout@v2

      - name: Build Seahorse
        run: |
          gem build seahorse.gemspec
          gem install seahorse-$(<VERSION).gem
        working-directory: ./seahorse

      - name: Download generated test SDK
        uses: actions/download-artifact@v2
        with:
          name: white_label
          path: white_label

      - name: Type checks
        run: |
          gem install steep
          steep check
        working-directory: ./white_label

  ruby-integration-specs:
    needs: [generate-test-sdk]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0']

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Download generated test SDK
        uses: actions/download-artifact@v2
        with:
          name: white_label
          path: white_label

      - name: Copy Gemfile
        run: |
          cp seahorse/Gemfile white_label/

      - name: Install gems
        run: |
          bundle config set --local without 'docs repl'
          bundle install
        working-directory: ./white_label

      - name: Tests
        run: bundle exec rspec -I ../seahorse/lib
        working-directory: ./white_label
