name: Codegen CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 8

jobs:
  generate-test-sdk:
    name: Generate the test sdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: test
      working-directory: codegen
      run:
        ./gradlew :smithy-ruby-codegen-test:build
    - name: Upload Generated Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: generated_test_sdk
        path: codegen/smithy-ruby-codegen-test/build/smithyprojections/smithy-ruby-codegen-test/source/ruby-codegen/weather
