name: Codegen CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 8

jobs:
  generate-test-sdk:
    name: Generate the test sdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: test
      working-directory: codegen
      run:
        ./gradlew :smithy-ruby-codegen-test:build
    - name: Upload Generated Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: generated_test_sdk
        path: sample_service_real

  ruby-integegration-specs:
    needs: [generate-test-sdk]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0'] # TODO: jruby versions do not currently work because of spec's dependency on OJ


    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Download generated sdk
        uses: actions/download-artifact@v2
        with:
          name: generated_test_sdk
          path: sample_service_real

      - name: Copy Gemfile
        run: |
          cp seahorse/Gemfile sample_service_real/          

      - name: Inspect
        run: |
          pwd
          ls

      - name: Install gems
        run: |
          bundle config set --local without 'docs repl'
          bundle install
        working-directory: ./sample_service_real

      - name: Tests
        run: bundle exec rspec
        working-directory: ./sample_service_real
