name: Downstream Codegen CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 17
  ruby_version: 3.3

jobs:

  aws-sdk-v4-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: publish smithy-ruby to maven local
        run: bundle exec rake codegen:publish-local

      - name: v4 setup and build
        run: |
          git clone --depth 1 https://github.com/alextwoods/aws-sdk-ruby-v4
          cd aws-sdk-ruby-v4
          bundle config local.Hearth ../
          bundle config disable_local_branch_check true
          bundle update
          bundle exec rake codegen:build

      - name: v4 core gem tests
        working-directory: aws-sdk-ruby-v4
        run: bundle exec rake test:core

      - name: v4 protocol tests
        working-directory: aws-sdk-ruby-v4
        run: bundle exec rake test:protocol-tests
