name: Hearth CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  ruby_version: 3.2

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Unit tests
        run: bundle exec rake test:hearth

  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: Steep Check
        run: bundle exec rake steep:hearth

      - name: RBS Validate
        run: bundle exec rake rbs:hearth

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rake rubocop:hearth
