name: Hearth CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  ruby_version: 3.3

jobs:
  hearth-rbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'rbs test'
          bundle install

      - name: Steep
        run: rake steep:hearth

      - name: RBS
        run: rake rbs:hearth

  hearth-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Supported ruby versions
        ruby: [jruby-9.4, '3.0', 3.1, 3.2, 3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gems
        run: |
          bundle config set --local with 'test'
          bundle install

      - name: Test
        run: rake test:hearth

  hearth-rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'development'
          bundle install

      - name: Rubocop
        run: rake rubocop:hearth
