name: Hearth CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Unit tests
        run: bundle exec rake test:hearth

  steep:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Steep Check
        run: bundle exec rake steep:hearth

      - name: RBS Validate
        run: bundle exec rake rbs:hearth

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install
        working-directory: hearth

      - name: Rubocop
        run: bundle exec rubocop -E -S
        working-directory: hearth
