name: Hearth CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install
        working-directory: hearth

      - name: Unit tests
        run: bundle exec rspec
        working-directory: hearth

  steep:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install
        working-directory: hearth

      - name: Type checks
        run: bundle exec steep check
        working-directory: hearth

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install
        working-directory: hearth

      - name: Rubocop
        run: bundle exec rubocop -E -S
        working-directory: hearth
