name: Rails Codegen CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 17
  ruby_version: 3.3

jobs:
  railsjson-rbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.java_version }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'rbs test'
          bundle install

      - name: Build SDK
        run: bundle exec rake codegen:build

      - name: Steep Checks
        run: bundle exec rake steep:rails_json

      - name: RBS Checks
        run: bundle exec rake rbs:rails_json

  railsjson-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [jruby-9.4, '3.0', 3.1, 3.2, 3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.java_version }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gems
        run: |
          bundle config set --local with 'test'
          bundle install

      - name: Build SDK
        run: bundle exec rake codegen:build

      - name: RailsJson Protocol Specs
        run: bundle exec rake test:rails_json
