name: Rubocop
on: [push]

jobs:
  seahorse-rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Bundle install
        run: |
          gem install bundler
          bundle install
        working-directory: ./seahorse

      - name: Rubocop
        run: bundle exec rubocop -E -S
        working-directory: ./seahorse
