name: RubyCI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0'] # TODO: jruby versions do not currently work because of spec's dependency on OJ


    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          bundle config set --local without 'docs repl'
          bundle install
        working-directory: ./seahorse

      - name: Tests
        run: bundle exec rspec
        working-directory: ./seahorse
