name: RubyCI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0', jruby-9.1, jruby-9.2]


    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
      	working-directory: ./seahorse
        run: |
          bundle config set --local without 'docs repl'
          bundle install

      - name: Tests
      	working-directory: ./seahorse
        run: bundle exec rspec
